### ISSUE TITLE
Isn't relying on Number.prototype.toString not being generic dangerous?

### ISSUE THREAD

**Issue by mgol** [ljharb/is-number-object#1]
Isn't relying on Number.prototype.toString not being generic dangerous? Some `toString` methods have been made generic in the past, e.g. `RegExp.prototype.toString`.

**Comment by ljharb** [comment]
It's not dangerous until the spec decides to change it; which it's not likely to.

Regardless, there will *always* be a brand-checking method for every builtin (except `Error`, at the moment), so even if `toString` were made generic, there would always be *something* left available.

**Comment by mgol** [comment]
My worry is not about all brand-checking methods to disappear for Number but that if `Number.prototype.toString` was ever made generic, this package would break. It can be updated but old code would remain broken. If future ECMAScript designers wanted to make `Number.prototype.toString` generic they'd hit web compatibility issues because of code in this module and the proposal would have to be withdrawn.

**Comment by ljharb** [comment]
1. Why would we ever want to make it generic?
1. There must *always* be one non-generic method for Numbers; if not toString, which would you recommend?
