### ISSUE TITLE
Package is not published as a NPM module

### ISSUE THREAD

**Issue by binayatdelhi** [ljharb/is-number-object#15]
Please publish this latest package on NPM. 
When I'm doing "npm view is-number-object" I can see only is-number-object@1.0.3

Latest tag 1.0.4 is not published. Getting following error  
is-number-object: No matching version found for is-number-object@^1.0.4

**Comment by ljharb** [comment]
It is published; just like the issue you filed on is-boolean-object, this is likely caused by a broken internal registry.

https://npmjs.com/is-number-object clearly shows v1.0.4 is published.
